# Generated by Django 5.1.15 on 2026-05-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='orders.order')),
                ('supplier_org', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to='organizations.organization')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to='orders.order')),
                ('source_supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_invoices', to='invoicing.supplierinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.supplierinvoice')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.clientinvoice')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice'], name='invoicing_c_invoice_1d1b19_idx')],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'order_item'), name='uniq_ci_item')],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier_org', 'status', '-created_at'], name='invoicing_s_supplie_f326f4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['order', 'status'], name='invoicing_s_order_i_bcee4d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['client_org', 'status', '-created_at'], name='invoicing_c_client__7746fe_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['order', 'status'], name='invoicing_c_order_i_d28c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoiceitem',
            index=models.Index(fields=['invoice'], name='invoicing_s_invoice_df9cc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'order_item'), name='uniq_si_item'),
        ),
    ]
