# Generated by Django 5.1.15 on 2026-05-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('quotes', '0001_initial'),
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='rfqs.rfq'),
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier_org',
            field=models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='rfq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rfqs.rfqitem'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['rfq', 'status'], name='quotes_quot_rfq_id_4a9564_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['supplier_org', '-created_at'], name='quotes_quot_supplie_fa9f85_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier_org'), name='uniq_quote_per_rfq_supplier'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote'], name='quotes_quot_quote_i_c36844_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteitem',
            constraint=models.UniqueConstraint(fields=('quote', 'rfq_item'), name='uniq_quote_item_per_rfq_item'),
        ),
    ]
