# Generated by Django 5.1.15 on 2026-05-03 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproduct_available_quantity_estimate_and_more'),
        ('organizations', '0005_organization_auto_quote_review_window'),
        ('quotes', '0002_initial'),
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='admin_held_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='applied_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='auto_send_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='final_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='final_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplierproduct'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (manual, legacy alias)'), ('DRAFT_AUTO', 'Draft (auto-generated)'), ('DRAFT_MANUAL', 'Draft (manual)'), ('PENDING_ADMIN', 'Pending admin review'), ('SUBMITTED', 'Submitted to client'), ('WITHDRAWN', 'Withdrawn'), ('AWARDED', 'Awarded'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'auto_send_at'], name='quotes_quot_status_a54c52_idx'),
        ),
    ]
