# Generated by Django 5.1.15 on 2026-05-03 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_quote_beat_schedule'),
        ('rfqs', '0003_alter_rfq_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (manual, legacy alias)'), ('DRAFT_AUTO', 'Draft (auto-generated)'), ('DRAFT_MANUAL', 'Draft (manual)'), ('PENDING_ADMIN', 'Pending admin review'), ('SUBMITTED', 'Submitted to client'), ('WITHDRAWN', 'Withdrawn'), ('AWARDED', 'Awarded'), ('PARTIALLY_AWARDED', 'Partially awarded'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=24),
        ),
        migrations.CreateModel(
            name='QuoteLineSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='quotes.quote')),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='quotes.quoteitem')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_selections', to='rfqs.rfq')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rfqs.rfqitem')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['rfq', 'quote'], name='quotes_quot_rfq_id_1fd62c_idx')],
                'constraints': [models.UniqueConstraint(fields=('rfq', 'rfq_item'), name='uniq_line_selection_per_rfq_item')],
            },
        ),
    ]
