# Generated by Django 5.1.15 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quote_status_quotelineselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
