[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/landing/index.html"
  to = "/landing/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
