# Generated by Django 5.1.15 on 2026-05-03 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('CATEGORY', 'Per-category'), ('CLIENT', 'Per-client')], max_length=12)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'scope_id'], name='pricing_mar_scope_9c9d69_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_id'), name='uniq_margin_per_scope')],
            },
        ),
    ]
