# Generated by Django 5.1.15 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=8)),
                ('date_key', models.CharField(max_length=12)),
                ('value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'date_key'], name='core_docume_kind_1e07d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'date_key'), name='uniq_doc_seq_kind_date')],
            },
        ),
    ]
