# Generated by Django 5.1.15 on 2026-05-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='organizations.organization')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RfqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('pack_type_code', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.masterproduct')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfqs.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='RfqVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='rfqs.rfq')),
                ('supplier_org', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['client_org', 'status', '-created_at'], name='rfqs_rfq_client__e8a38c_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', '-published_at'], name='rfqs_rfq_status_9d1aff_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqitem',
            index=models.Index(fields=['rfq', 'line_no'], name='rfqs_rfqite_rfq_id_ae659d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfqitem',
            constraint=models.UniqueConstraint(fields=('rfq', 'line_no'), name='uniq_rfq_line_no'),
        ),
        migrations.AddConstraint(
            model_name='rfqvisibility',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier_org'), name='uniq_rfq_supplier_visibility'),
        ),
    ]
