# Generated by Django 5.1.15 on 2026-05-03 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproduct_available_quantity_estimate_and_more'),
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='source',
            field=models.CharField(choices=[('CATALOG', 'From master catalog'), ('CUSTOM_REQUEST', 'Custom request (off-catalog)')], default='CATALOG', max_length=16),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='free_text_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='free_text_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='specs_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rfqitem',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='master_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.masterproduct'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='pack_type_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
