# Generated by Django 5.1.15 on 2026-05-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0002_rfq_source_rfqitem_free_text_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('AWARDED', 'Awarded'), ('PARTIALLY_AWARDED', 'Partially awarded')], default='DRAFT', max_length=20),
        ),
    ]
