# Generated by Django 5.1.15 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_alter_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='rfq_number',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
