# Generated by Django 5.1.15 on 2026-05-02 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='DRAFT', max_length=12)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_deliveries', to='organizations.organization')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='orders.order')),
                ('supplier_org', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.deliverynote')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=12)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='organizations.organization')),
                ('delivery_note', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grn', to='fulfillment.deliverynote')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dn_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fulfillment.deliverynoteitem')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.goodsreceiptnote')),
            ],
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['order', 'status'], name='fulfillment_order_i_2b9875_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['client_org', 'status', '-created_at'], name='fulfillment_client__6b8eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['supplier_org', 'status', '-created_at'], name='fulfillment_supplie_9f35b4_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynoteitem',
            index=models.Index(fields=['delivery_note'], name='fulfillment_deliver_a00b82_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverynoteitem',
            constraint=models.UniqueConstraint(fields=('delivery_note', 'order_item'), name='uniq_dn_item'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptnote',
            index=models.Index(fields=['client_org', 'status', '-created_at'], name='fulfillment_client__aa783f_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptitem',
            index=models.Index(fields=['grn'], name='fulfillment_grn_id_580394_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptitem',
            constraint=models.UniqueConstraint(fields=('grn', 'dn_item'), name='uniq_grn_item'),
        ),
    ]
