# Generated by Django 5.1.15 on 2026-05-03 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0005_organization_auto_quote_review_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('JOINT', 'Joint (legacy)'), ('CPO', 'Client PO'), ('SPO', 'Supplier PO')], db_index=True, default='JOINT', max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('IN_FULFILLMENT', 'In fulfillment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['transaction_ref', 'type'], name='orders_orde_transac_7ea39a_idx'),
        ),
    ]
