# Generated by Django 5.1.15 on 2026-05-02 20:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_c1c99d_idx'), models.Index(fields=['target_ct', 'target_id', '-created_at'], name='audit_audit_target__efddb4_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='audit_audit_payload_911b1c_gin')],
            },
        ),
    ]
