# Generated by Django 5.1.15 on 2026-05-03 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_po_number_order_transaction_ref_order_type_and_more'),
        ('organizations', '0005_organization_auto_quote_review_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approves_for', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_nodes', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'member'], name='approvals_a_organiz_1e2726_idx'), models.Index(fields=['direct_approver'], name='approvals_a_direct__27b0c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'member'), name='uniq_approval_node_per_org_member')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_chain', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'status'], name='approvals_a_order_i_9248d6_idx'), models.Index(fields=['approver', 'status'], name='approvals_a_approve_9647a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'order_in_chain'), name='uniq_approval_task_per_order_chain')],
            },
        ),
    ]
