# Generated by Django 5.1.15 on 2026-05-02 19:07

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('default_uom', models.CharField(blank=True, max_length=32)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('image_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=16)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('image_keys', models.JSONField(default=list)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('pack_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=16)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('deprecation_reason', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_products', to='catalog.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type_code', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('display_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.bundle')),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.masterproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name_en', models.CharField(max_length=255)),
                ('proposed_name_ar', models.CharField(max_length=255)),
                ('proposed_description_en', models.TextField(blank=True)),
                ('proposed_description_ar', models.TextField(blank=True)),
                ('proposed_sku', models.CharField(blank=True, max_length=64)),
                ('proposed_brand', models.CharField(blank=True, max_length=128)),
                ('image_keys', models.JSONField(default=list)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('proposed_pack_types', models.JSONField(default=list)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_products', to='catalog.category')),
                ('created_master_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.masterproduct')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='product_addition_requests', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type_code', models.CharField(max_length=32)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moq', models.PositiveIntegerField(default=1)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('auto_quote', models.BooleanField(default=False)),
                ('availability_status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('DISCONTINUED', 'Discontinued')], default='IN_STOCK', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('low_stock_threshold', models.IntegerField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_listings', to='catalog.masterproduct')),
                ('organization', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'display_order'], name='catalog_cat_parent__a3bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'level'], name='catalog_cat_is_acti_5d2b30_idx'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['status', 'display_order'], name='catalog_bun_status_d134ff_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=models.Index(fields=['category', 'status'], name='catalog_mas_categor_4a6d13_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=models.Index(fields=['status', '-created_at'], name='catalog_mas_status_2dbc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_mas_search__803bce_gin'),
        ),
        migrations.AddIndex(
            model_name='bundleitem',
            index=models.Index(fields=['bundle', 'display_order'], name='catalog_bun_bundle__28e677_idx'),
        ),
        migrations.AddConstraint(
            model_name='bundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'master_product', 'pack_type_code'), name='uniq_bundle_item'),
        ),
        migrations.AddIndex(
            model_name='productadditionrequest',
            index=models.Index(fields=['organization', 'status'], name='catalog_pro_organiz_081556_idx'),
        ),
        migrations.AddIndex(
            model_name='productadditionrequest',
            index=models.Index(fields=['status', '-created_at'], name='catalog_pro_status_c638f9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['organization', 'approval_status'], name='catalog_sup_organiz_fe3712_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['master_product', 'approval_status'], name='catalog_sup_master__4494c3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['approval_status', '-created_at'], name='catalog_sup_approva_e44d6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'master_product', 'pack_type_code'), name='uniq_supplier_product_per_pack'),
        ),
    ]
