# Generated by Django 5.1.15 on 2026-05-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='available_quantity_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='fulfillment_mode',
            field=models.CharField(choices=[('EXPRESS', 'Express'), ('MARKET', 'Market')], default='MARKET', max_length=12),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_notes',
            field=models.TextField(blank=True),
        ),
    ]
