# Generated by Django 5.1.15 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplierproduct_available_quantity_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='master_product_code',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
