# Generated by Django 5.1.15 on 2026-05-02 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested')], default='DRAFT', max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('legal_name_ar', models.CharField(blank=True, max_length=255)),
                ('cr_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, default='SA', max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CR', 'Commercial registration'), ('VAT', 'VAT certificate'), ('BANK_LETTER', 'Bank letter'), ('ID_CARD', 'ID card'), ('OTHER', 'Other')], max_length=24)),
                ('storage_key', models.CharField(max_length=512)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission')),
            ],
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['organization', '-created_at'], name='kyc_kycsubm_organiz_fe79a4_idx'),
        ),
        migrations.AddIndex(
            model_name='kycsubmission',
            index=models.Index(fields=['status'], name='kyc_kycsubm_status_1d4f35_idx'),
        ),
        migrations.AddIndex(
            model_name='kycdocument',
            index=models.Index(fields=['submission'], name='kyc_kycdocu_submiss_6996e1_idx'),
        ),
    ]
