# Generated by Django 5.1.15 on 2026-05-02 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.clientinvoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client_org', '-paid_at'], name='payments_pa_client__c1fbbf_idx'), models.Index(fields=['invoice'], name='payments_pa_invoice_fcb1dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='invoicing.supplierinvoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier_org', models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier_org', '-paid_at'], name='payments_pa_supplie_3499f3_idx'), models.Index(fields=['invoice'], name='payments_pa_invoice_ca148d_idx')],
            },
        ),
    ]
