# Generated by Django 5.1.15 on 2026-05-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
