# Generated by Django 5.1.15 on 2026-05-02 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WafeqContactSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafeq_contact_id', models.CharField(db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wafeq_contact', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WafeqInvoiceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafeq_invoice_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PUSHED', 'Pushed'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('last_error', models.TextField(blank=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wafeq_sync', to='invoicing.clientinvoice')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='wafeq_wafeq_status_395fbc_idx')],
            },
        ),
    ]
