# Generated by Django 5.1.15 on 2026-05-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('pack_type_code', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_SIGNATURES', 'Pending signatures'), ('SIGNED', 'Signed'), ('ORDER_ISSUED', 'Order issued'), ('CANCELLED', 'Cancelled')], default='PENDING_SIGNATURES', max_length=24)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_org', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_contracts', to='organizations.organization')),
                ('client_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
