# Generated by Django 5.1.15 on 2026-05-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='quotes.quote'),
        ),
    ]
