# Generated by Django 5.1.15 on 2026-05-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contracts', '0002_initial'),
        ('organizations', '0001_initial'),
        ('rfqs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rfqs.rfq'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier_org',
            field=models.ForeignKey(limit_choices_to={'type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_contracts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supplier_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractitem',
            name='master_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.masterproduct'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_org', 'status'], name='contracts_c_client__031220_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['supplier_org', 'status'], name='contracts_c_supplie_309dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', '-created_at'], name='contracts_c_status_e5aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractitem',
            index=models.Index(fields=['contract', 'line_no'], name='contracts_c_contrac_2e9fa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractitem',
            constraint=models.UniqueConstraint(fields=('contract', 'line_no'), name='uniq_contract_line_no'),
        ),
    ]
