# Generated by Django 5.1.15 on 2026-05-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplierproduct_available_quantity_estimate_and_more'),
        ('organizations', '0005_organization_auto_quote_review_window'),
        ('rfqs', '0003_alter_rfq_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SAVED', 'Saved'), ('SUBMITTED', 'Submitted (converted to RFQ)'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=12)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='organizations.organization')),
                ('submitted_rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rfqs.rfq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type_code', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.cart')),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.masterproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_catalogs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.companycatalog')),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.masterproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.masterproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='shopping_ca_user_id_90455e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'expires_at'], name='shopping_ca_status_eedff7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'organization'), name='uniq_active_cart_per_user_org'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='shopping_ca_cart_id_d00d67_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'master_product', 'pack_type_code'), name='uniq_cart_item'),
        ),
        migrations.AddIndex(
            model_name='companycatalog',
            index=models.Index(fields=['organization', 'name'], name='shopping_co_organiz_344127_idx'),
        ),
        migrations.AddConstraint(
            model_name='companycatalog',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_company_catalog_name'),
        ),
        migrations.AddIndex(
            model_name='companycatalogitem',
            index=models.Index(fields=['catalog', '-added_at'], name='shopping_co_catalog_70fa4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='companycatalogitem',
            constraint=models.UniqueConstraint(fields=('catalog', 'master_product'), name='uniq_catalog_item'),
        ),
        migrations.AddIndex(
            model_name='favourite',
            index=models.Index(fields=['user', '-created_at'], name='shopping_fa_user_id_6556aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'master_product'), name='uniq_favourite_per_user_product'),
        ),
    ]
