# Generated by Django 5.1.15 on 2026-05-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('SUPPLIER', 'Supplier')], max_length=16)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('KYC_PENDING', 'KYC pending'), ('KYC_REVIEW', 'KYC under review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='INVITED', max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('legal_name_ar', models.CharField(blank=True, max_length=255)),
                ('public_id', models.CharField(max_length=32, unique=True)),
                ('cr_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('subscription_status', models.CharField(default='none', max_length=16)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'status'], name='organizatio_type_a06ce9_idx'), models.Index(fields=['public_id'], name='organizatio_public__462b59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('BUYER', 'Buyer'), ('APPROVER', 'Approver'), ('VIEWER', 'Viewer')], max_length=16)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='organizatio_user_id_fe1569_idx'), models.Index(fields=['organization', 'role'], name='organizatio_organiz_e82976_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='uniq_membership_user_org')],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('BUYER', 'Buyer'), ('APPROVER', 'Approver'), ('VIEWER', 'Viewer')], max_length=16)),
                ('kind', models.CharField(choices=[('OWNER', 'Owner invite (from MWRD staff)'), ('TEAM', 'Team invite (from org owner)')], max_length=8)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invites_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='organizatio_organiz_a1fe8f_idx'), models.Index(fields=['email', 'status'], name='organizatio_email_829a3d_idx')],
            },
        ),
    ]
