# Generated by Django 5.1.15 on 2026-05-03 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_backfill_platform_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='expected_monthly_volume_sar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='signup_intent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='signup_source',
            field=models.CharField(choices=[('CLIENT_FORM', 'Public client form'), ('SUPPLIER_FORM', 'Public supplier form'), ('ADMIN_INVITED', 'Created by MWRD staff')], default='ADMIN_INVITED', max_length=24),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('account_type', models.CharField(choices=[('CLIENT', 'Client'), ('SUPPLIER', 'Supplier')], max_length=16)),
                ('company_name', models.CharField(max_length=255)),
                ('signup_intent', models.TextField(blank=True)),
                ('expected_monthly_volume_sar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PENDING_CALLBACK', 'Pending callback'), ('CALLBACK_COMPLETED', 'Callback completed'), ('ACTIVATED', 'Activated'), ('REJECTED', 'Rejected')], default='PENDING_CALLBACK', max_length=24)),
                ('callback_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('activation_token_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('activation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('callback_completed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resulting_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='organizatio_status_1c8620_idx'), models.Index(fields=['email', 'status'], name='organizatio_email_7f901e_idx')],
            },
        ),
    ]
