# Generated by Django 5.1.15 on 2026-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_expected_monthly_volume_sar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_quote_review_window',
            field=models.CharField(choices=[('INSTANT', 'Send immediately'), ('WINDOW_30M', 'Hold 30 minutes for review'), ('WINDOW_2H', 'Hold 2 hours for review')], default='WINDOW_30M', max_length=16),
        ),
    ]
